name: publish-latest

on:
  push:
    branches:
      - master

jobs:
  publish-android-emulator-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        env:
          REPO_URL: ${{ github.repository }}
        run: |
          docker build . --tag ghcr.io/$REPO_URL:latest
          docker push ghcr.io/$REPO_URL:latest

